fix

diff --git a/.github/workflows/gatling_run.yml b/.github/workflows/gatling_run.yml
--- a/.github/workflows/gatling_run.yml
+++ b/.github/workflows/gatling_run.yml
@@ -65,6 +65,31 @@ jobs:
           echo "B64_AUTH: ${B64_AUTH}"
           
           curl -i -X POST "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token?grant_type=client_credentials" -H 'Content-Type: application/json' -H "Authorization: Basic $B64_AUTH"
+          
+
+
+
+
+      - name: Debug Auth access - auth
+        id: get_token
+        shell: bash
+        env:
+          CLIENT_ID: ${{ secrets.GATLING_CLIENT_ID }}
+          CLIENT_SECRET: ${{ secrets.GATLING_CLIENT_SECRET }}
+        run: |
+          BASIC_AUTH=$(echo -n "$CLIENT_ID:$CLIENT_SECRET" | base64 | tr -d '\n')
+          RESPONSE=$(curl --fail-with-body --verbose -s -X POST "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token?grant_type=client_credentials" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Basic $BASIC_AUTH")
+          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
+          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
+            echo "Failed to extract access token."
+            echo "Response was: $RESPONSE"
+            exit 1
+          fi
+          echo "::add-mask::$TOKEN"
+          echo "token=$TOKEN" >> $GITHUB_OUTPUT
+
 
       - name: Start Gatling
         env:
@@ -93,6 +118,7 @@ jobs:
           export CLIENT_SECRET="${CLIENT_SECRET}"
           echo "Running: ./gradlew ${ARGS[*]}"
           CLIENT_ID="${CLIENT_ID}" CLIENT_SECRET="${CLIENT_SECRET}" ./gradlew "${ARGS[@]}"
+
 
       - name: Upload Gatling reports
         if: always()
